version: 2
sphinx:
   configuration: docs/conf.py
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - cd docs && pip install --exists-action=w --no-cache-dir -r requirements.txt
